### ISSUE TITLE
change resnet 18 to  wide_resnet50_2

### ISSUE THREAD

**Issue by wjx213** [SimonThomine/RememberingNormality#4] opened 2024-05-09 06:41 UTC
Hello,Thank you very much for your work. However, when I change 'resnet18' to 'wide_resnet50_2' in the 'config.yaml' file and run 'trainRM_RD.py', I encounter an error. May I ask how I can adjust other parameters if I want to change the backbone to 'wide_resnet50_2' so that the model can run? Thank you very much for your response.

**Comment by SimonThomine** [comment] 2024-05-09 09:09
Hello, you're right, I forgot to adapt the memory modules for the wide resnet architecture (bottleneck instead of basicblock). The problem is now fixed. Please let me know if you encounter any other problem.

**Comment by wjx213** [comment] 2024-05-11 03:01
thank you for your reply, the problem has been fixed，but the results differ slightly from the paper, but I'm still very grateful for your work!

**Comment by SimonThomine** [comment] 2024-05-11 05:30
No problem :) Let me know if you find any problem in the code that could explain the slight difference in results.

**Closed as completed by SimonThomine** 2024-05-11 05:30 UTC
